/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion;

import java.util.Arrays;

public class App {

    public static  void main(String[] args)
    {

        int[] arr = { 4,1,2,3};
        System.out.println(Arrays.toString(Insertion.sort(arr)));
        Insertion.printArray(arr);
        Insertion insertion =new Insertion();
    }
}
